plugins:
  - jekyll-feed
  - jekyll-relative-links
auto: true
highlighter: rouge
baseurl: /agdb/
title: Another game development blog
relative_links:
  enabled:     true
  collections: true
markdown: CustomProcessor

disable_disk_cache: true
incremental: false